# Site settings
title: Dota 2 @ Western Washington University
email: wwudota@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Western Washington University's Official Dota2 eSports Organization
baseurl:
url: /
twitter_username: wwudota
# github_username:  jekyll

# Build settings
markdown: kramdown
